-- Custom SQL migration file, put your code below! --
-- Category every watch repair order goes under, and the watch brands the intake form starts with.
-- Brands not listed here are added by the shop from the form.
INSERT INTO `model_categories` (`id`, `name`, `slug`) SELECT 'vm3ivfm83og3qqvt8yy4c73z', 'Watches', 'watches' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_categories` WHERE `slug` = 'watches');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'g21m7rv93xvm50fn48w18yg0', 'Amazfit', 'watch-amazfit', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Amazfit');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'dg0ay166mb6w8xfslu8bayv7', 'Apple', 'watch-apple', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Apple');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'vgms7fhizpxceyttownouy89', 'Casio', 'watch-casio', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Casio');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'h5zhicx5lu6djjx22m67q7ha', 'Citizen', 'watch-citizen', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Citizen');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'qhtip4y25bzd33p8cg449e2s', 'Festina', 'watch-festina', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Festina');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'gv6kio9y73rv6lfaixxvzkc2', 'Fossil', 'watch-fossil', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Fossil');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'e609ztqobpaoaf29fpnhwjr3', 'Garmin', 'watch-garmin', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Garmin');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'j9ygvh6m8jnt0pi3gnong6bi', 'Guess', 'watch-guess', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Guess');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'lss39k3g5dzjw0tmiq3c5nat', 'Hamilton', 'watch-hamilton', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Hamilton');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'tau7vicr5epz6vhtp7bjixq4', 'Huawei', 'watch-huawei', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Huawei');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'wqwag8zsa37x8ojr3d1y6z1v', 'John L. Cook', 'watch-john-l-cook', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'John L. Cook');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'b6i1npsc8hv7va9ad78exwqs', 'Knock Out', 'watch-knock-out', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Knock Out');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'ydv0g1521eon1vdnbhciqgxs', 'Mido', 'watch-mido', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Mido');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'h4l12u9w6owgmgzncqkiexee', 'Mistral', 'watch-mistral', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Mistral');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'i868cig0fjz5lewcdxcgohx8', 'Montreal', 'watch-montreal', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Montreal');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'lz13gtm30jmufylyqstcoz0k', 'Omega', 'watch-omega', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Omega');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'lut787rmi4m6wq6yhvny4plr', 'Orient', 'watch-orient', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Orient');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'sne55njw57t31s9bp1y7lkyq', 'Q&Q', 'watch-q-q', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Q&Q');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'e6c7vgz1ogtey9gh6s025hua', 'Rolex', 'watch-rolex', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Rolex');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'thmj79dd2eokmqw1gc87urni', 'Samsung', 'watch-samsung', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Samsung');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'xdjaruv8dswwcmhaeajmtbkz', 'Seiko', 'watch-seiko', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Seiko');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'nh7z38r822785texgk7bz7nr', 'Swatch', 'watch-swatch', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Swatch');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'whx8dhj6gh061bpfpenjekdj', 'Tag Heuer', 'watch-tag-heuer', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Tag Heuer');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'wgqiy8b4i9vvcgu8ur4gnyi5', 'Timex', 'watch-timex', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Timex');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'ht2pacxkagvmcsocr7rdnk6x', 'Tissot', 'watch-tissot', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Tissot');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'x24e187sw51pf1slqjzcinkb', 'Tressa', 'watch-tressa', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Tressa');--> statement-breakpoint
INSERT INTO `model_makers` (`id`, `name`, `slug`, `url`, `maker_kind`) SELECT 'vgsp36ew76txisec2ifj6ql4', 'Xiaomi', 'watch-xiaomi', '', 'watch' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM `model_makers` WHERE `maker_kind` = 'watch' AND `name` = 'Xiaomi');
